# Generated by Django 5.2.8 on 2025-12-23 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('jugado', models.BooleanField(default=False)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_locales', to='prode.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_visitantes', to='prode.equipo')),
            ],
        ),
    ]
