# Generated by Django 5.2.8 on 2025-12-23 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0002_partido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('equipo_elegido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prode.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prode.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'partido')},
            },
        ),
    ]
